# fly.toml app configuration file generated for activity on 2023-09-29T20:23:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "activity"
primary_region = "dfw"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5002"

[http_service]
  internal_port = 5002
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="database"
  destination="/mnt/database"
